# -*- yaml-indent-offset: 2; -*-

name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  PEW_TOPLEVEL: __pew__

jobs:
  sanity:
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          # - snapshot
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    ##
    ## This is believed to be an unresolved issue from GitHub workflow where
    ## the pending jobs can be accidentally canceled for an unknown reason
    ## saying
    ##   "Canceling since a higher priority waiting request for
    ##   'CI-refs/heads/master' exists"
    ## Currently a workaround is to disable the concurrency.
    ##
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    #   cancel-in-progress: false

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Check out this config
        uses: actions/checkout@v3

      - name: Test - Fresh startup with package installation
        run: ./${PEW_TOPLEVEL}/tests/test-init.sh $(pwd)

      - name: Test - Normal startup
        run: ./${PEW_TOPLEVEL}/tests/test-init.sh $(pwd)

      - name: Test - Mini startup
        run: ./${PEW_TOPLEVEL}/tests/test-init-mini.sh $(pwd)

      - name: Test - pewcfg unittest
        run: ./${PEW_TOPLEVEL}/site-lisp/pewcfg/tests/run-tests.sh $(pwd)/${PEW_TOPLEVEL}/site-lisp/pewcfg
