# -*- yaml-indent-offset: 2; -*-

name: Emacs basic sanity

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  dot_emacs_d:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          # - snapshot

    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Checkout PEW
        uses: actions/checkout@v3

      - name: Test - Fresh startup with package installation
        run: ./pew/tests/test-init.sh $(pwd)

      - name: Test - Normal startup
        run: ./pew/tests/test-init.sh $(pwd)

      - name: Test - Mini startup
        run: ./pew/tests/test-init-mini.sh $(pwd)

      - name: Test - pewcfg unittests
        run: ./pew/site-lisp/pewcfg/tests/run-tests.sh $(pwd)
